### ISSUE TITLE
Adding several stations: When adding several modules, they all use the same config

### ISSUE THREAD

**Issue by esnalabu** [JonasTriki/MMM-Bysykkel#1]
Living in the proximity of two stations and with two frequent destinations, I want to add this splendid module twice. This works, kind of, but all the modules are using the config from the module first defined. 

Of course, this might be the wrong approach. Maybe being able to add several stations to one module would be the preferred way of achieving this.

**Comment by JonasTriki** [comment]
Hi there! Sorry for the extremely late reply.

That's a good point and your use-case is very realistic; this module does not work very well when adding it multiple times to a single MagicMirror!

An idea I had in mind was to implement the feature you are requesting (letting you specify multiple from/to station ID's) and make the module iterate over the from/to station ID pairs by fading them in/out after a certain time interval (e.g. iterate to next from/to pair every 10 seconds). I will look into this asap 😊

**Comment by JonasTriki** [comment]
I have now added support for adding several stations to one module See README for more information. Thank you for the issue!
