### ISSUE TITLE
Module not loading, suspect client identifier

### ISSUE THREAD

**Issue by oysteinhusby** [JonasTriki/MMM-Bysykkel#2]
Hi Jonas,

I'm unable to load the module despite following your instructions and Bysykkel's. 
[Your link to creating a new client id](https://developer.oslobysykkel.no/clients/new) is no longer available, but from what I gather from Bysykkel's API, this is no longer necessary. (One can simply name the identifier oneself).

Any idea why I'm unsuccessful?

**Comment by JonasTriki** [comment]
Hi Øystein,

Thank you for your bug report. There had been a few changes to the Oslo bysykkel API since I created this module, but it should be fixed now! Now you don't need the client ID for Oslo Bysykkel, and can simply configure it as Bergen for example (see docs).
